'use strict';

const jestRules = {
  'consistent-test-it': 'off',
  'expect-expect': 'error',
  'lowercase-name': 'off',
  'no-alias-methods': 'off',
  'no-commented-out-tests': 'error',
  'no-conditional-expect': 'off',
  'no-deprecated-functions': 'off',
  'no-disabled-tests': 'warn',
  'no-duplicate-hooks': 'off',
  'no-export': 'error',
  'no-focused-tests': 'error',
  'no-hooks': 'off',
  'no-identical-title': 'error',
  'no-if': 'off',
  'no-interpolation-in-snapshots': 'off',
  'no-jasmine-globals': 'error',
  'no-jest-import': 'error',
  'no-large-snapshots': 'off',
  'no-mocks-import': 'error',
  'no-restricted-matchers': 'off',
  'no-standalone-expect': 'error',
  'no-test-callback': 'error',
  'no-test-prefixes': 'error',
  'no-test-return-statement': 'off',
  'prefer-called-with': 'off',
  'prefer-expect-assertions': 'off',
  'prefer-hooks-on-top': 'off',
  'prefer-spy-on': 'off',
  'prefer-strict-equal': 'off',
  'prefer-to-be-null': 'off',
  'prefer-to-be-undefined': 'off',
  'prefer-to-contain': 'off',
  'prefer-to-have-length': 'off',
  'prefer-todo': 'off',
  'require-to-throw-message': 'off',
  'require-top-level-describe': 'off',
  'valid-describe': 'error',
  'valid-expect-in-promise': 'error',
  'valid-expect': 'error',
  'valid-title': 'off',
};

module.exports = {
  jestRules,
};
